#!/usr/bin/env bash

[[ -z "$SUDO_USER" ]] || {
    [[ "$SUDO_USER" == root ]] || { SUDO_USER= sudo -u "$SUDO_USER" "$0" "$@"; exit $?; }
}

BLEND_COMMAND="sudo pacman $@" blend enter arch
ret=$?

exit $ret
